config/routes.rb
Rails.application.routes.draw do
get '/blogs' => 'blog#index'
root 'blog#index'
get 'blogs/new' => 'blog#new'
get '/blogs/:id' => 'blog#show', as: 'show_blog'
post '/blogs' => 'blog#create'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/blog.rb
class Blog < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/blog_controller.rb
class BlogController < ApplicationController
    def index
        @blogs = Blog.all
    end
    def show
        @blog = Blog.find(params[:id])
    end
    def new
        @blog = Blog.new
    end
    def create
        @blog = Blog.create(blog_params)
        if @blog.valid?
            redirect_to blogs_path
        end
    end
end

private
def blog_params
    params.require(:blog).permit(:title, :content) 
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blog_helper.rb
module BlogHelper
end

app/views/blog/index.html.erb
<h1>Our Blog</h1>

<% @blogs.each do |blog| %>
    <ul>
        <li><%= link_to blog.title, show_blog_path(blog) %></li>
    </ul>
<% end %>

app/views/blog/new.html.erb
<h3>Create a New Blog</h3>
<%= form_with model: @blog do |form| %>

  <%= form.label :title %>
  <%= form.text_field :title %>

  <br>
  <%= form.label :content %>
  <%= form.text_field :content %>

  <br>
  <%= form.submit 'Add Blog' %>
<% end %>
<br/>
<%= link_to 'Home Page', '/blogs' %>

app/views/blog/show.html.erb
<h3><%= @blog.title %></h3>
<p><%= @blog.content %></p>
<%= link_to 'Home Page', '/blogs' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BlogChallenge</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>